### ISSUE TITLE
asteroid hangar not exactly attached anymore in KSP 1.3.1 (hangar v3.3.2)

### ISSUE THREAD

**Issue by LouisCyfer** [allista/hangar#191]
I'm aware of currently it's only supported for KSP 1.3.0 according to the .versions, there is no message in the log.

However I'm sure the hangars shouldn't look like that and maybe new KSP 1.3.1 asteroids might just work as intended (this one was a 1.3.0 captured one) but that is untested yet.

Most likely the hangars should not look like this:
![hangars_grappleissue](https://user-images.githubusercontent.com/19025056/31523002-346deede-afb1-11e7-86f1-d5d2e23d402e.png)

**Comment by allista** [comment]
There's no build for 1.3.1, so things shouldn't work. Wait until I fix incompatibilities with the new API and publish new versions of the mods.

**Comment by allista** [comment]
As it turns out, the Hangar does not need a rebuild for 1.3.1. So what you see is indeed a bug. But rather in KSP itself then in the Hangar:
http://bugs.kerbalspaceprogram.com/issues/16087#change-82157

What's important is that I've made a workaround. Though it works only for old saves that are yet unaffected by the bug.

**Comment by LouisCyfer** [comment]
Ahh that makes sense considering this bug report and the issue old saves are integers, new ones are floats.

Basicially the asteroids just get a new random seed float, which cause the deformation (I hope i understood that from there).

I'm glad you found a workaround for old saves!
